export const buttonStyles = {
  position: "fixed",
  bottom: "20px",
  right: "20px",
  width: "50px",
  height: "50px",
  backgroundColor: "#3498db",
  color: "white",
  textAlign: "center",
  borderRadius: "50%",
  cursor: "pointer",
  boxShadow: "0 2px 10px rgba(0, 0, 0, 0.2)",
  zIndex: "1000",
  border: "none",
  display: "flex",
  "justify-content": "center",
  "align-items": "center",
};

export const iframeStyles = {
  display: "none",
  position: "fixed",
  bottom: "90px",
  right: "20px",
  width: "400px",
  height: "70vh",
  border: "none",
  borderRadius: "10px",
  boxShadow: "0 2px 10px rgba(0, 0, 0, 0.2)",
  zIndex: "1000",
};
